### ISSUE TITLE
Quimup seems calculate MPD config files incorrectly

### ISSUE THREAD

**Issue by kkkrackpot** [ronalde/quimup-packaging#3]
Hi!

Thanks for your work on Quimup, it's really very neat and nice tool!

But now I have a little problem with it -- every time I lauch Quimup it opens a warning message:

> **Multiple configuration files found!**
> -  /etc/mpd.conf
> 
> The default choice is : /etc/mpd.conf
> 
> Please make sure that MPD is also using this. You can set MPD to use a specific configuration file in /etc/default/mpd.

However, I'm sure I don't have any MPD configs besides _/etc/mpd.conf_...

Looks like line 2579 in _/src/qm_mpdcom.cpp_ has an extra _config_count++_ operation

Could you please check that?

This everytime warning is not a real problem, of course, but it's rather annoying...

Regards,
Alex

**Comment by ronalde** [comment]
Hi Alex, sorry I missed your question. Could you please pick this up with the quimup developer at http://www.coonsden.com. 

I just made the Debian packages.

Regards,
Ronald
